# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build text-justifier`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t text-justifier`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system text-justifier && \
          adduser --system -G text-justifier text-justifier

COPY dist/text-justifier text-justifier
RUN chown -R text-justifier:text-justifier .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix text-justifier --omit=dev -f install

CMD [ "node", "text-justifier" ]
